### ISSUE TITLE
Duplicated token

### ISSUE THREAD

**Issue by EthanOKung** [codesoap/mycolog#3]
I was looking through the token generation code and it didn't seem that there is a check for duplicated token (though the chance of a duplicate token being generated is very low) either in token.go or in modifications.go where the generateToken function is called.  Maybe there is a check somewhere else that I just missed?  If not, I'm working on an alternate token generation method where tokens are generated in sequence and you just read the last database entry token and increment it for the new token.  

Would something like this work?  Code attached as .txt file here.  I haven't worked with .go nor sqlite databases before so don't know the code for pulling the last database entry.  Is that easy to do in token.go file?

[token_v2.txt](https://github.com/codesoap/mycolog/files/10834391/token_v2.txt)

I implemented token with a length 2 since that already gives 1000 tokens and the shorter length makes labeling easier.  But it isn't hard to increase the token length if needed.

**Comment by codesoap** [comment]
You are correct, tokens are not checked for duplicates at all. However, I have made sure, that mycolog will continue to work without any issue, even if a duplicate token occurs.

This is a conscious design choice. Random tokens make it possible to have, e.g. petri dishes of different mycolog-databases mixed with each other, without having problems, because the different mycolog instances run through the same sequence of tokens.

The chance of a duplicate is relatively low: Tokens have a length of four, where each character can each be one of 33 characters. Using the square approximation of the birthday paradox, we can see that you would have to have roughly 1000 tokens (`sqrt(33^4)`), which you actively use, to have a 50% chance of a duplicate.

If you plan on handling such large amounts of components, it is easy to increase the token length to five (needs ca. 6000 tokens for a 50% chance on a duplicate) or even higher.

If you'd still prefer to have a guarantee on uniqueness, you can use the IDs of the components (the numbers that start with "#").

**Comment by EthanOKung** [comment]
Good point about mixing databases.  I wasn't thinking about that use but that would make random tokens very useful.  

Now that I see the software is really only using the ID #s to keep track of entries but not the tokens: 1) it's not a big deal to have a chance of an occasional duplicate token, and 2) for the purpose of preferring short tokens, one can just directly edit the database with a SQLite editor and change the token names without affecting anything else.
